name: lint-checker-python
run-name: apply-lint-checker
on:
  push:
    branches:
      - main
jobs:
  check-lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup python
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'
      - name: install black and isort
        run: python -m pip install pip && python -m pip install black && pip install isort
      - name: check black
        run: python -m black . --check
      - name: check isort
        run: python -m isort --profile black . --check
